name: energy-performance-diagnosis
channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - pip
  - pip:
      - ramp-workflow
      - osfclient